import type { NextPage } from 'next'
import Head from 'next/head'
import Video from '../components/Cards/Video'
import Categoriesbar from '../components/Categoriesbar'

const Home: NextPage = () => {
  return (
    <div className='app_content'>
      <Head>
        <title>YouTube clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Categoriesbar />
      <div className='container'>
        <div className='row'>
          {[...Array(16)].map((_, index) =>
            <div className='col-lg-3 col-md-3 col-12 mb-4'>
              <Video key={index} />
            </div>)}
        </div>
      </div>
    </div>
  )
}

export default Home
